### ISSUE TITLE
Waveform samples at each stage

### ISSUE THREAD

**Issue by francislata** [w-transposed-x/hifi-gan-denoising#2]
It would be awesome to provide some audio samples at each stage of the training to see how it is doing.

**Comment by 742617000027** [comment]
Audio examples are logged into tensorboard during validation (you can control how often validation takes place in the hparams). [Here are two audio examples at step 725,000](https://github.com/w-transposed-x/hifi-gan-denoising/files/5655068/725000.zip). I'll see to producing more examples and posting them somewhere.

**Comment by francislata** [comment]
@742617000027 I will close this issue for now but I'll be watching this issue if you wish to update it with more samples down the road.

Thank you!
